version: "3.9"
services:
  app:
    build:
        context: .
        dockerfile: php.dockerfile
    volumes:
      - ./vendor:/var/www/html/vendor
      - ./node_modules:/var/www/html/node_modules
      - ./:/var/www/html
      - ./php/upload.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on:
        - mysql
        - nginx

  mysql:
    image: mysql:5.7.30
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

  node:
      build:
          context: .
          dockerfile: node.dockerfile
      ports:
          - 5173:5173
      volumes:
          - ./:/var/www/html
          - ./node_modules:/var/www/html/node_modules
